jasm.jasm.*:
  type: config_entity
  label: 'JASM services config'
  mapping:
    id:
      type: string
      label: 'ID'
    uuid:
      type: string
      label: 'UUID'
    label:
      type: label
      label: 'Label'
    preset:
      type: string
      label: 'Preset'
      translatable: true
    status:
      type: boolean
      label: 'Enabled'
    service_page_url:
      type: string
      label: 'Service page url'
    color:
      type: string
      label: 'Color'
      translatable: true
    weight:
      type: integer
      label: 'Weight'
